# username: postgres password : root
#psql -U postgres
version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: 'root'
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data


