# If taking Docker Mastery, this is the same file you created in 
# ./compose-assignment-2
# If taking Swarm Mastery, this is your starting point for adding secrets :)
# reminder, this needs to change to 3.1 version to use secrets!
version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # volumes:
    #   - ./mongo:/data/db


